services:

  keycloak-secret-loader:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak-secret-loader
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/keycloak
    command: >
      sh -c "
      echo 'Ожидание готовности Keycloak...' &&
      while ! curl -s http://keycloak:8080; do sleep 5; done &&
      echo 'Keycloak готов - начинаем получение секретов' &&
      chmod +x /app/scripts/get-secrets.sh &&
      sh /app/scripts/get-secrets.sh"
    depends_on:
      - keycloak
      - keycloak-config-loader
    networks:
      - kafka-net

  keycloak-config-loader:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak-config-loader
    volumes:
      - ./keycloak:/keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_REALM=master
    entrypoint: [ ]
    command: >
      /bin/sh -c "
      echo 'Ожидание готовности Keycloak...' &&
      while ! curl -s http://keycloak:8080; do
        sleep 5;
      done &&
      echo 'Keycloak готов - начинаем конфигурацию' &&
      echo 'Загрузка скоупов...' &&
      sh /app/scripts/upload-scopes-to-keycloak.sh &&
      echo 'Загрузка клиентов...' &&
      sh /app/scripts/upload-clients-to-keycloak.sh"
    depends_on:
      - keycloak
    networks:
      - kafka-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - kafka-net

  kafka:
    container_name: kafka
    image: apache/kafka:4.0.0
    ports:
      - 9092:9092     # для Kafka UI внутри Docker
      - 29092:29092   # для доступа из локального приложения
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka-net

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - kafka-net

  kibana:
    image: kibana:8.12.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - kafka-net

  logstash:
    image: logstash:8.12.0
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
    networks:
      - kafka-net

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8000:8000"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

  accounts-db:
    image: postgres:latest
    container_name: accounts_db_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: accounts_db
    ports:
      - "5430:5432"
    networks:
      - kafka-net

  accounts:
    container_name: accounts
    build:
      context: ./accounts
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_R2DBC_URL=r2dbc:postgresql://accounts-db:5432/accounts_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts-db:5432/accounts_db
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8001:8001"
    depends_on:
      - accounts-db
      - keycloak-secret-loader
    networks:
      - kafka-net

  blocker:
    container_name: blocker
    build:
      context: ./blocker
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8002:8002"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

  cash:
    container_name: cash
    build:
      context: ./cash
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8003:8003"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

  exchange:
    container_name: exchange
    build:
      context: ./exchange
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8004:8004"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

  exchange-generator:
    container_name: exchange-generator
    build:
      context: ./exchange-generator
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8005:8005"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

  notifications:
    container_name: notifications
    build:
      context: ./notifications
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8006:8006"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

  transfer:
    container_name: transfer
    build:
      context: ./transfer
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8007:8007"
    depends_on:
      - keycloak-secret-loader
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge