services:

  keycloak-secret-loader:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak-secret-loader
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/keycloak
    command: >
      sh -c "
      echo 'Ожидание готовности Keycloak...' &&
      while ! curl -s http://keycloak:8080; do sleep 5; done &&
      echo 'Keycloak готов - начинаем получение секретов' &&
      chmod +x /app/scripts/get-secrets.sh &&
      sh /app/scripts/get-secrets.sh"
    depends_on:
      - keycloak
      - keycloak-config-loader

  keycloak-config-loader:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak-config-loader
    volumes:
      - ./keycloak:/keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_REALM=master
    entrypoint: [ ]
    command: >
      /bin/sh -c "
      echo 'Ожидание готовности Keycloak...' &&
      while ! curl -s http://keycloak:8080; do
        sleep 5;
      done &&
      echo 'Keycloak готов - начинаем конфигурацию' &&
      echo 'Загрузка скоупов...' &&
      sh /app/scripts/upload-scopes-to-keycloak.sh &&
      echo 'Загрузка клиентов...' &&
      sh /app/scripts/upload-clients-to-keycloak.sh"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8000:8000"
    depends_on:
      - keycloak-secret-loader

  accounts-db:
    image: postgres:latest
    container_name: accounts_db_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: accounts_db
    ports:
      - "5430:5432"

  accounts:
    container_name: accounts
    build:
      context: ./accounts
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_R2DBC_URL=r2dbc:postgresql://accounts-db:5432/accounts_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts-db:5432/accounts_db
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8001:8001"
    depends_on:
      - accounts-db
      - keycloak-secret-loader

  blocker:
    container_name: blocker
    build:
      context: ./blocker
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8002:8002"
    depends_on:
      - keycloak-secret-loader

  cash:
    container_name: cash
    build:
      context: ./cash
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8003:8003"
    depends_on:
      - keycloak-secret-loader

  exchange:
    container_name: exchange
    build:
      context: ./exchange
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8004:8004"
    depends_on:
      - keycloak-secret-loader

  exchange-generator:
    container_name: exchange-generator
    build:
      context: ./exchange-generator
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8005:8005"
    depends_on:
      - keycloak-secret-loader

  notifications:
    container_name: notifications
    build:
      context: ./notifications
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8006:8006"
    depends_on:
      - keycloak-secret-loader

  transfer:
    container_name: transfer
    build:
      context: ./transfer
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
    ports:
      - "8007:8007"
    depends_on:
      - keycloak-secret-loader