server:
  port: 8007

spring:
  application:
    name: transfer
  config:
    import: optional:consul://${CONSUL_HOST:localhost}:8500
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      config:
        enabled: true
        prefixes: config,secrets
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/master}
      client:
        registration:
          transfer-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: transfer-client
            client-secret: ${CLIENT_SECRET:Sbv2HTFhjQhdlt49JVLukoXH1Dlf05sv}
            scope: accounts.read,accounts.write,blocker.read,exchange.read,notification.write
            client-authentication-method: client_secret_post
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/master}

client:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://accounts:8001}
  blocker:
    url: ${BLOCKER_SERVICE_URL:http://blocker:8002}
  exchange:
    url: ${EXCHANGE_SERVICE_URL:http://exchange:8004}
  notifications:
    url: ${NOTIFICATIONS_SERVICE_URL:http://notifications:8006}