server:
  port: 8000

spring:
  application:
    name: front

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    check-template-location: true
    cache: false

  security:
    oauth2:
      client:
        registration:
          front-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${CLIENT_ID:front-client}
            client-secret: ${CLIENT_SECRET:LLtTlDhsJJ2lfN5c0oHtcb0zdLQyvkXQ}
            scope: exchange.read,accounts.read,accounts.write,cash.write,transfer.write
            client-authentication-method: client_secret_basic
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/master}

client:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://accounts:8001}
  cash:
    url: ${CASH_SERVICE_URL:http://cash:8003}
  exchange:
    url: ${EXCHANGE_SERVICE_URL:http://exchange:8004}
  transfer:
    url: ${TRANSFER_SERVICE_URL:http://transfer:8007}