server:
  port: 8000

spring:
  application:
    name: front

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    check-template-location: true
    cache: false

  config:
    import: optional:consul://${CONSUL_HOST:localhost}:8500
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      config:
        enabled: true
        prefixes: config,secrets
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true

  security:
    oauth2:
      client:
        registration:
          front-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${CLIENT_ID:front-client}
            client-secret: ${CLIENT_SECRET:8lHWta5ggYFsrJN5eUEKn3j8YmZqLbSl}
            scope: exchange.read,accounts.read,accounts.write,cash.write,transfer.write
            clientAuthenticationMethod: client_secret_post
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_SERVER:http://localhost:8080/realms/master}

client:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://accounts:8080}
  cash:
    url: ${CASH_SERVICE_URL:http://cash:8080}
  exchange:
    url: ${EXCHANGE_SERVICE_URL:http://exchange:8080}
  transfer:
    url: ${TRANSFER_SERVICE_URL:http://transfer:8080}