{ { - if .Values.secret.create } }
apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.secret.name } }
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: security
type: Opaque
data:
  kibana_password: { { .Values.secret.kibanaPassword | b64enc | quote } }
  { { - end } }
