server:
  port: 8010

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        service-name: api-gateway
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: gateway
        prefer-ip-address: true
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: exchange-route
          uri: lb://exchange
          predicates:
            - Path=/exchange/**
          filters:
            - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: exchangeServiceCircuitBreaker
                fallbackUri: forward:/exchange-fallback
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: accounts-route
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: accountsServiceCircuitBreaker
                fallbackUri: forward:/accounts-fallback
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: cash-route
          uri: lb://cash
          predicates:
            - Path=/cash/**
          filters:
            - RewritePath=/cash/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: cashServiceCircuitBreaker
                fallbackUri: forward:/cash-fallback
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: transfer-route
          uri: lb://transfer
          predicates:
            - Path=/transfer/**
          filters:
            - RewritePath=/transfer/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: transferServiceCircuitBreaker
                fallbackUri: forward:/transfer-fallback
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: blocker-route
          uri: lb://blocker
          predicates:
            - Path=/blocker/**
          filters:
            - RewritePath=/blocker/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: blockerServiceCircuitBreaker
                fallbackUri: forward:/blocker-fallback
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,PATCH,DELETE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false

resilience4j:
  circuitbreaker:
    instances:
      exchangeServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      accountsServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      cashServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      transferServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      blockerServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG