server:
  port: 8001

spring:
  application:
    name: accounts

  r2dbc:
    url: ${SPRING_DATASOURCE_R2DBC_URL:r2dbc:postgresql://localhost:5432/bankapp_accounts}
    username: ${SPRING_DATASOURCE_USER:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
    pool:
      enabled: true # Включение пула соединений
      initial-size: 10 # Начальное количество соединений в пуле
      max-size: 50 # Максимальное количество соединений
      max-idle-time: 30s # Время бездействия соединения перед закрытием
      max-life-time: 10m # Максимальное время жизни соединения
      validation-query: SELECT 1 # SQL-запрос для проверки работоспособности соединения

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankapp_accounts}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USER:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}

  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankapp_accounts}
    user: ${SPRING_DATASOURCE_USER:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}

  config:
    import: optional:consul://${CONSUL_HOST:localhost}:8500
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      config:
        enabled: true
        prefixes: config,secrets
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/bankapp}
      client:
        registration:
          accounts-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${CLIENT_ID:accounts-client}
            client-secret: ${CLIENT_SECRET:PAsZ470oShhYzY9qlVy35yty0tcWZhp7}
            scope: exchange.read,accounts.read,accounts.write,cash.write,transfer.write
            client-authentication-method: client_secret_post
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/master}

client:
  notifications:
    url: ${NOTIFICATIONS_SERVICE_URL:http://notifications:8006}