apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_R2DBC_URL: {{ tpl .Values.environment.SPRING_DATASOURCE_R2DBC_URL . | quote }}
  SPRING_DATASOURCE_URL: {{ tpl .Values.environment.SPRING_DATASOURCE_URL . | quote }}
  SPRING_DATASOURCE_USER: {{ .Values.environment.SPRING_DATASOURCE_USER | quote }}
  # SPRING_DATASOURCE_PASSWORD would typically come from a secret, not this ConfigMap.
