replicaCount: 1

image:
  repository: bankapp-notifications
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8006

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts:
    - host: notifications.test.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80