services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${KUBECONFIG_PATH}:/root/.kube/config
      - $HOME/.kube:/var/jenkins_home/.kube
      - $HOME/.minikube:/var/jenkins_home/.minikube
      - ~/.minikube:/var/jenkins_home/.minikube
    networks:
      - minikube

networks:
  minikube:
    external: true

volumes:
  jenkins_home: