server:
  port: 8005

spring:
  application:
    name: exchange-generator

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      client-id: exchange-generator
      fail-fast: true
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: TRACE

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always