kind: ConfigMap
apiVersion: v1
metadata:
  name: { { include "cash.fullname" . } }
  labels:
    { { - include "cash.labels" . | nindent 4 } }
data:
  management.zipkin.tracing.endpoint: { { tpl .Values.environment.ZIPKIN_TRACING_ENDPOINT . | quote } }
  management.tracing.sampling.probability: { { .Values.environment.ZIPKIN_SAMPLING_PROBABILITY | quote } }