server:
  port: 8006

spring:
  application:
    name: notifications

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      client-id: notifications
      fail-fast: true
    consumer:
      group-id: notifications
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-commit: true
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: '*'

logging:
  level:
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: TRACE