server:
  port: 8004

spring:
  application:
    name: exchange
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      config:
        enabled: false
        prefixes: config
        defaultContext: application

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/master}